# Generated by Django 4.2.16 on 2024-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiledimage',
            name='tiles_folder',
        ),
    ]
