# Generated by Django 4.2.16 on 2024-11-15 13:43

from django.db import migrations, models
import tiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_remove_tiledimage_tiles_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiledimage',
            name='original_image',
            field=models.FileField(upload_to='originals/', validators=[tiles.models.validate_image_extension]),
        ),
    ]
